[project]
name = "eduweaver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent-framework>=1.0.0b260130",
    "agent-framework-devui>=1.0.0b260130",
    "azure-identity>=1.26.0b1",
    "azure-storage-blob>=12.29.0b1",
]
